# Generated by Django 6.0.7 on 2026-08-30 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='core_bookin_client__9e263a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['freelancer', 'status'], name='core_bookin_freelan_5c94ad_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='core_bookin_status_2da2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='core_chatme_room_id_1b52ec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-issued_at'], name='core_invoic_status_627686_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='core_messag_recipie_ffa7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-created_at'], name='core_messag_sender__9e7f42_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='core_paymen_created_f77624_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'hourly_rate'], name='core_profil_role_2ded71_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'is_verified'], name='core_profil_role_70b4df_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'availability'], name='core_profil_role_a9c96e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'experience_years'], name='core_profil_role_955182_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'rating'], name='core_review_reviewe_411d99_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', '-created_at'], name='core_review_reviewe_56640a_idx'),
        ),
    ]
